#!/usr/bin/env node

var program  = require('commander');
var config   = require('./lib/config').config;
var manifest = require('./lib/manifest').read();
var async    = require('async');
var fs       = require('fs');
var download = require('./lib/download').download;

program.parse(process.argv);

if(program.args.length !== 1){
    console.log('Usage: sb-builder download [options] <URL>');
    process.exit();
}

var videoURL = program.args[0];

console.log("Downloading video from "+videoURL+" ...");
return download(manifest, videoURL, opts, function(err){
        console.log("Finished downloading video.");
        process.exit();
    }
);
