#!/usr/bin/env node

var program  = require('commander');
var config   = require('./config').config;
var manifest = require('./lib/manifest').read();
var async    = require('async');
var fs       = require('fs');
var render   = require('./lib/render').render;

program.parse(process.argv);

if(program.args.length !== 1){
    console.log('Usage: sb-builder render [options] <FOLDER>');
    process.exit();
}

var folder = program.args[0];

console.log("Rendering soundboard '"+manifest.metadata.name+"' into folder '"+folder+"':");
return render(manifest, folder, function(err){
        console.log("Finished rendering soundboard.");
        process.exit();
    }
);
