#!/usr/bin/env node

var program = require('commander');
var config  = require('./lib/config').config;
var fs      = require('fs-extra');
var log     = require('./lib/log').log('sb-builder');

program.parse(process.argv);

if(program.args.length !== 1){
    log.info('Usage: sb-builder init [options] <name>');
    process.exit();
}

var name = program.args[0];
var manifest = require('./lib/manifest').create(name);
var folders = [
    config.tmpPath,
    config.sourcesPath,
    config.soundsPath
];
log.info('Creating folders ...');
folders.forEach(function(folder){
    fs.mkdirSync(folder);
});
log.info('Finished!');

