#!/usr/bin/env node

// Require our dependencies
var program = require('commander');
var ytdl    = require('ytdl-core');
var fs      = require('fs-extra');
var async   = require('async');
var log     = console.log;
var mkdirp  = require('mkdirp');
var URL     = require('url');
var qs      = require('querystring');
var sprintf = require("sprintf-js").sprintf;
var spawn   = require('child_process').spawnSync;
var config  = require('./lib/config').config;
var pjson = require('./package.json');

program.version(pjson.version)
        .command('init     <name>'    , 'kickoff a new soundboard project')
        .command('download <URL>'     , 'download sound from Youtube URL provided, and save metadata in manifest')
        .command('snip     <ID|URL>'  , 'open external sound edition application to extract sound snippet')
        .command('fix      <SNIP_ID>' , 'fix (re-extract or re-edit) sound snippet')
        .command('render'             , 'generates soundboard website')
        //.command('manifest'         , 'Perform operations based on the manifest')
        .parse(process.argv);

if(!program.args.length){ program.help(); }

