#!/usr/bin/env node

var program = require('commander');
var config  = require('./lib/config').config;
var fs      = require('fs-extra');
var log     = require('./lib/log').log('sb-builder');
var init    = require('./lib/init').init;

program.parse(process.argv);

if(program.args.length !== 1){
    log.info('Usage: sb-builder init [options] <name>');
    process.exit();
}

var name = program.args[0];

console.log("Initializing soundboard "+name+" in the current folder ...");
return init(name, function(err){
  console.log("Soundboard initialized.");
  process.exit();
}),
